import * as HeadTag from 'next/head';

export const Head = (props) => {
  return (
    <HeadTag>
      <title>{props.title}</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
      <link href="//netdna.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
    </HeadTag>
  )
}
