import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React from 'react';

import Count from '../components/Count';
import { userService } from 'services';
import { Link } from 'components';

export async function getServerSideProps() {
  return {
    props: {
      stars: 12345
    },
  };
}

const Home = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          <div>Next stars: {props.stars}</div>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <Count/>
        </main>
      </div>
      <div className="p-4">
        <div className="container">
          <h1>Hi {userService.userValue?.firstName}!</h1>
          <p>You&apos;re logged in with Next.js & JWT!!</p>
          <p><Link href="/users">Manage Users</Link></p>
        </div>
      </div>
    </>
  );
};

export default Home;
